### ISSUE TITLE
Keybindings sometimes don't work entirely(?)

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/sowm#15]
I can't reproduce this at all. Any help is appreciated. @Dobbie03

Source: https://forum.archlabslinux.com/t/void-linux-sowm-pfetch/3694

**Comment by tjtf2** [comment]
i think it might be a issue with the Makefile, whenever i update my keybindings/commands i have to do `sudo make clean install` instead of just `sudo make install`

**Comment by dylanaraps** [comment]
Question to whoever can reproduce this: Have you tried the current master (*the latest commit*)?

**Comment by AnalogCyan** [comment]
I was also having this issue and the current master fixes it for me.

**Comment by Dobbie03** [comment]
I will try with the new master and see how we go.  Basically I ```make clean install``` from the default config.h.  No changes other than that.

Will report back.

**Comment by Dobbie03** [comment]
I will try with the new master and see how we go.  Basically I ```make clean install``` from the default config.h.  No changes other than that.

Will report back.

**Comment by Dobbie03** [comment]
I cloned the latest master and I am still having the same issue.  What do you need log/info wise from me to help here?

**Comment by dylanaraps** [comment]
Thanks for getting in touch.

- Are you using a different keyboard layout?
- Does your keyboard differ in any way from "the default"?
    - Any settings changed in software?/
- Does `catwm` work?
    - It also uses Xlib and is "simple" like `sowm`.

**Comment by dylanaraps** [comment]
Also, try the latest master with https://github.com/dylanaraps/sowm/commit/35b12c796971fa5afd9ffeb393c365973c76237f

**Comment by Dobbie03** [comment]
Okay.  Here we go.

- no I am using the US layout.
- Anything relating to the keyboard sooftware wise I have removed.  I was using Ksuperkey but that and anything pertaining to it have been deleted or uninstalled.
- ```catwm``` also doesn't work for me.

Again I have tried with the latest master and am experiencing the same issues.  I'll get a install up and running on a laptop and test there as this ArchLabs build of mine is so old it could be something else entirely that is messing me around.

**Comment by dylanaraps** [comment]
The fact that `catwm` also doesn't work is reassuring. Does `dwm` work? If it does I'll take a poke through their source to see if `sowm`/`catwm` are doing anything differently and or "wrong". Thanks for testing, I appreciate it.

**Comment by Dobbie03** [comment]
@dylanaraps Yep, dwm works perfectly.

Once I get set up on a laptop I can get testing as well.

**Comment by dylanaraps** [comment]
Another commit to try: https://github.com/dylanaraps/sowm/commit/5b012c10be6eceb27c4dba7d9ae346160f123892

**Comment by Dobbie03** [comment]
Same issue still happening. I'd like to try this on a clean install.

**Comment by VerbTheNoun95** [comment]
Having the same issue on Void after `make clean install` with the latest commit. `sowm` starts up just fine with `exex sowm` in my `.xinitrc`, I have a terminal displayed that I can use to open firefox. Focus follows the mouse from terminal to browser, but none of the keybindings work.

**Comment by nerigardu** [comment]
I don't know if this is the same problem, but if I try to switch windows with Alt Tab after closing all windows, keybindings fail as well. I use sxhkd, and the only way to regain keybindings is to kill the Xserver and restart it.

It also occurs randomly from time to time.

Relevant (?) X11 error message seen after closing Xorg:  `xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)`

**Comment by slepe** [comment]
This happens for me when I enable numlock. See if it's the same for y'all.

**Comment by koutsie** [comment]
^ This but with caps lock :D

**Comment by clusterF** [comment]
This bug also affects my installation when numlock on .

**Comment by dylanaraps** [comment]
I have possibly fixed the issue in this commit: https://github.com/dylanaraps/sowm/commit/2292f86d7fb861a22aa5f076a82453ab6927e54b

Please try it out and let me know if it works. :)

**Comment by slepe** [comment]
I built the latest version. Half the bindings don't seem to work at all now. 
The only bindings that work are move and resize. 
Though I haven't had the issue with caps lock.

**Comment by slepe** [comment]
Built the latest version. Had a problem with some binding but that was on my end. The issue still persists for me with numlock or capslock are activated.

**Comment by clusterF** [comment]
updated with commit but still have same issue with numlock.

**Comment by dylanaraps** [comment]
Fixed.....

**Comment by Dobbie03** [comment]
Hi Dylan

I checked out sowm again a couple days back and the num-lock enable issue still exists for me.  Nothing works while num-lock is on.

**Comment by dylanaraps** [comment]
Hm. Neither of my laptops have had a numlock so I haven't been able to test. The issue has gone away with all of the modifier keys I do have. Can you at least confirm that the issue no longer occurs with capslock?

**Comment by Dobbie03** [comment]
Keybinds work fine with caps lock enabled.

**Comment by kjjjnob** [comment]
Confirm the same problem here. Numlock kill all keybinds. With caps lock also works perfect

**Comment by medgar123** [comment]
https://github.com/dylanaraps/sowm/pull/81 might fix this
